# 脚本跟目录
# 将会载入该目录下所有以 ".groovy" 结尾的文件
# 如果文件以 "-" 开头则不会载入
scriptDir: 'plugins/TabooScript/scripts'

# 脚本默认名称前缀
# 如果没有为脚本设置名称，则会根据文件名称命名
scriptPrefix: 'ts_'

# 脚本插件名称前缀
# 脚本将会以插件的形式载入到服务器当中，并使用该前缀。
pluginPrefix: '#'

# 触发器检查范围
# 以下包中的触发器将不需要补全包名
# 如 "org.bukkit.event.player.AsyncPlayerChatEvent" 则可以省略为 "AsyncPlayerChatEvent"
eventPackages:
- org.bukkit.event.block
- org.bukkit.event.command
- org.bukkit.event.enchantment
- org.bukkit.event.entity
- org.bukkit.event.hanging
- org.bukkit.event.inventory
- org.bukkit.event.player
- org.bukkit.event.server
- org.bukkit.event.vehicle
- org.bukkit.event.weather
- org.bukkit.event.world
- org.spigotmc.event.player
- org.spigotmc.event.entity
- me.skymc.taboolib.events
- me.skymc.taboolib.events.itag

# 默认导入包
# 实际上是被添加到原本import列表的后面
# 这种默认导入可能会带来干扰
defaultImport:
- org.bukkit.attribute.*
- org.bukkit.block.*
- org.bukkit.boss.*
- org.bukkit.enchantments.*
- org.bukkit.entity.*
- org.bukkit.entity.minecart.*
- org.bukkit.generator.*
- org.bukkit.inventory.*
- org.bukkit.inventory.meta.*
- org.bukkit.material.*
- org.bukkit.material.types.*
- org.bukkit.metadata.*
- org.bukkit.potion.*
- org.bukkit.util.BlockIterator
- org.bukkit.util.NumberConversions
- org.bukkit.util.Vector
- org.bukkit.util.BlockVector
- org.bukkit.*
- me.skymc.taboolib.database.GlobalDataManager
- me.skymc.taboolib.database.PlayerDataManager
- me.skymc.taboolib.inventory.ItemUtils
- me.skymc.taboolib.itemnbtapi.NBTItem
- me.skymc.taboolib.itemnbtapi.NBTFile
- me.skymc.taboolib.itemnbtapi.NBTEntity
- me.skymc.taboolib.mysql.hikari.HikariHandler
- me.skymc.taboolib.mysql.builder.SQLHost
- me.skymc.taboolib.mysql.builder.SQLTable
- me.skymc.taboolib.mysql.builder.SQLExecutor
- me.skymc.taboolib.mysql.builder.SQLColumn
- me.skymc.taboolib.mysql.builder.SQLColumnOption
- me.skymc.taboolib.mysql.builder.SQLColumnType
- me.skymc.taboolib.object.WeightCollection
- me.skymc.taboolib.scoreboard.ScoreboardUtil
- me.skymc.taboolib.sound.SoundPack
- me.skymc.taboolib.support.SupportWorldGuard
- me.skymc.taboolib.timeutil.TimeFormatter
- me.skymc.taboolib.common.configuration.*
- me.skymc.taboolib.common.json.*
- me.skymc.taboolib.common.nms.*
- me.skymc.taboolib.common.packet.*
- me.skymc.taboolib.common.pathfinder.*
- me.skymc.taboolib.common.uril.*